### ISSUE TITLE
Store logs of failed builds

### ISSUE THREAD

**Issue by Luzifer** [Luzifer/gobuilder#27]
In order to debug failed builds store their logs into storage being able to handle many single files (IPFS?) and reference them in Redis & on repository page.

**Comment by jbenet** [comment]
Would it be helpful to have timed pins on ipfs? (Eg pin something for a certain amount of time)

—

**Comment by Luzifer** [comment]
Hmm for this I would not use that feature but cleanup according to the index in the Redis… But in general this sounds like a very useful feature!
