### ISSUE TITLE
numbered builds

### ISSUE THREAD

**Issue by whyrusleeping** [Luzifer/gobuilder#5]
It would be nice if each build was numbered, so users could refer to a particular build. Also, it would be nice if a `VERSION` file was included in the zip, so we know exactly which git commit sha it was built from

**Comment by jbenet** [comment]
Re version file, see #4

**Comment by Luzifer** [comment]
As soon as a tag is on a commit on build time the build result is conserved with that tag name. (See https://gobuilder.me/github.com/Luzifer/gobuilder for an example) The `master` tag is overwritten on every build.

**Comment by jbenet** [comment]
@Luzifer excellent-- so @whyrusleeping, maybe we should start pushing tags with every version change.

@Luzifer have you thought about integrating with github releases?

**Comment by Luzifer** [comment]
@jbenet Not yet. Will keep that in mind and read documentation… (But I fear this will need further permissions (write) to the repositories…)

**Comment by jbenet** [comment]
yeah-- wish github scoped their permissions...

**Comment by Luzifer** [comment]
This is implemented in #7 with a configuration parameter for the file itself.

**Comment by Luzifer** [comment]
Implemented in a126e81
