### ISSUE TITLE
change .zip to .tar.gz on linux prebuild

### ISSUE THREAD

**Issue by ghost** [Luzifer/gobuilder#63]
Hi, 
It's not important but, 
The precompiled binary for linux are .zip I would be preferable to have them in .tar.gz or anything standard to linux. unzip is not installed by default on many distrubutions.

**Comment by davidar** [comment]
:+1:

**Comment by Luzifer** [comment]
Will start to work on this after #62 is closed.

## TODO
- Add TGZ packing to builder process (Covered in #62)
- [ ] Display TGZ download links on repo page
- [ ] Display hashes for ZIP and TGZ on repo page
