### ISSUE TITLE
Idea: readme badge

### ISSUE THREAD

**Issue by jbenet** [Luzifer/gobuilder#67]
It would be nice if gobuilder had a prominent badge (like the npm badges) that people could put on their readme. 

it should have:
- a clear logo that can be recognized. (could be a package box with the gopher)
- the package name.
- maybe the package path?
- maybe the version? (branch/tag)
- maybe oses?
- npm example: https://nodei.co/

Possibility:

![](https://ipfs.io/ipfs/QmdmkiHXoGkSAMg4x7WChsdn1GEtJsBQLkogRP2VLdi6Uk/gobuilder-pkg.png)

(src: https://openclipart.org/detail/211800/package )

**Comment by Luzifer** [comment]
I like this idea!

Currently I'm using this badge to show people the way from the README to the download:

```
[![GoBuilder Download](https://badge.luzifer.io/v1/badge?color=5d79b5&title=Download&text=on GoBuilder)](https://gobuilder.me/github.com/Luzifer/dns_check)
```

Will keep this issue open and think about it.
